/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoedd;
import org.graphstream.graph.*; //importe de la libreria de graphstream

/**
 *
 * @author Nathaly
 */
public class WGrafo extends javax.swing.JFrame {
       //preguntar como pasar un dato de un JFrame a otro

    

    /**
     * Creates new form Linea1
     */
    
    public WGrafo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        B_back_3 = new javax.swing.JButton();
        B_show_graph = new javax.swing.JButton();
        B_add_sucursal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Grafo Stations");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 42, -1, -1));

        B_back_3.setText("Atrás");
        B_back_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_back_3ActionPerformed(evt);
            }
        });
        getContentPane().add(B_back_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 258, -1, -1));

        B_show_graph.setText("grafo");
        B_show_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_show_graphActionPerformed(evt);
            }
        });
        getContentPane().add(B_show_graph, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 105, -1, -1));

        B_add_sucursal.setText("añadir sucursal");
        getContentPane().add(B_add_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 181, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_back_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_back_3ActionPerformed
        W3 ventana = new W3();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B_back_3ActionPerformed

    private void B_show_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_show_graphActionPerformed
        WGrafo graf = new WGrafo();
        //graf.Graph(listaLines); //pasar grafo de la primera ventana
    }//GEN-LAST:event_B_show_graphActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(List l) {
        List lista = l;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WGrafo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_add_sucursal;
    private javax.swing.JButton B_back_3;
    private javax.swing.JButton B_show_graph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
